# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-14 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysDept',
            fields=[
                ('deptId', models.BigAutoField(db_column='dept_id', help_text='主键自增ID', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('deptName', models.CharField(db_column='dept_name', help_text='请输入部门名称', max_length=32, unique=True, verbose_name='部门名称')),
                ('deptLoc', models.CharField(db_column='dept_loc', help_text='请输入部门工作地点', max_length=32, verbose_name='部门工作地点')),
                ('deptStatus', models.SmallIntegerField(choices=[(0, '未激活'), (1, '激活')], db_column='dept_status', default=0, help_text='部门激活状态，0：未激活，1：激活', verbose_name='部门激活状态')),
                ('deptDesc', models.EmailField(db_column='dept_desc', help_text='请输入部门描述！', max_length=128, verbose_name='部门描述')),
                ('isDel', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], db_column='is_del', default=0, help_text='该记录是否被删除，0：未删除，1：已删除，默认为0', verbose_name='该记录是否被删除')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间', null=True, verbose_name='记录最后更新时间')),
            ],
            options={
                'verbose_name': '系统部门表',
                'verbose_name_plural': '系统部门表',
                'db_table': 'sys_dept',
            },
        ),
        migrations.CreateModel(
            name='SysTitle',
            fields=[
                ('titleId', models.BigAutoField(db_column='title_id', help_text='主键自增ID', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('titleName', models.CharField(db_column='title_name', help_text='请输入岗位名称', max_length=32, unique=True, verbose_name='岗位名称')),
                ('titleType', models.SmallIntegerField(choices=[(100, '普通员工'), (101, '项目ledear'), (102, '部门负责人'), (103, 'XXO'), (104, '临时用户')], db_column='title_type', help_text='岗位类型，100:普通员工，101:项目ledear，102:部门负责人，103:XXO，104:临时用户', verbose_name='岗位类型')),
                ('titleStatus', models.SmallIntegerField(choices=[(0, '未激活'), (1, '激活')], db_column='title_status', default=0, help_text='岗位激活状态，0：未激活，1：激活', verbose_name='岗位激活状态')),
                ('titleDesc', models.EmailField(db_column='title_desc', help_text='请输入岗位描述！', max_length=128, verbose_name='岗位描述')),
                ('isDel', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], db_column='is_del', default=0, help_text='该记录是否被删除，0：未删除，1：已删除，默认为0', verbose_name='该记录是否被删除')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间', null=True, verbose_name='记录最后更新时间')),
            ],
            options={
                'verbose_name': '系统岗位表',
                'verbose_name_plural': '系统岗位表',
                'db_table': 'sys_title',
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('userId', models.BigAutoField(db_column='user_id', help_text='主键自增ID', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('userName', models.CharField(db_column='user_name', help_text='请输入用户姓名', max_length=32, unique=True, verbose_name='用户姓名')),
                ('userPwd', models.CharField(db_column='user_pwd', help_text='请输入用户密码', max_length=64, verbose_name='用户密码')),
                ('userRole', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], db_column='user_role', default=0, help_text='是否为项目leader，1：是，0：否', verbose_name='是否为项目leader')),
                ('userStatus', models.SmallIntegerField(choices=[(0, '未激活'), (1, '激活')], db_column='user_status', default=1, help_text='用户激活状态，0：未激活，1：激活', verbose_name='用户激活状态')),
                ('userEmail', models.EmailField(db_column='user_email', default='xxx@dycd.com', help_text='请输入邮箱！', max_length=128, unique=True, verbose_name='用户邮箱')),
                ('userPhone', models.CharField(db_column='user_phone', default='11000000000', help_text='请输入手机号！', max_length=11, unique=True, verbose_name='用户手机号')),
                ('isDel', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], db_column='is_del', default=0, help_text='该记录是否被删除，0：未删除，1：已删除，默认为0', verbose_name='该记录是否被删除')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间', null=True, verbose_name='记录最后更新时间')),
                ('deptId', models.ForeignKey(db_column='dept_id', help_text='请选择部门', on_delete=django.db.models.deletion.CASCADE, to='account.SysDept', verbose_name='部门编号，外键')),
                ('titleId', models.ForeignKey(db_column='title_id', help_text='请输入职位', on_delete=django.db.models.deletion.CASCADE, to='account.SysTitle', verbose_name='职位编号，外键')),
                ('userMgrid', models.ForeignKey(db_column='user_mgrid', help_text='用户领导id，0为管理员用户，自外键', on_delete=django.db.models.deletion.CASCADE, to='account.SysUser', verbose_name='用户领导id')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'sys_user',
            },
        ),
    ]
