# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-14 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysGroup',
            fields=[
                ('groupId', models.BigAutoField(db_column='group_id', help_text='主键自增ID', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('groupName', models.CharField(db_column='group_name', help_text='请输入项目组名称!', max_length=32, unique=True, verbose_name='项目组名称（项目名）')),
                ('groupStatus', models.SmallIntegerField(choices=[(0, '未激活'), (1, '激活')], db_column='group_status', default=1, help_text='项目组状态，0：不可用，1：可用', verbose_name='项目组状态')),
                ('groupDesc', models.EmailField(db_column='group_desc', help_text='项目组描述！', max_length=128, verbose_name='项目组描述')),
                ('isDel', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], db_column='is_del', default=0, help_text='该记录是否被删除，0：未删除，1：已删除，默认为0', verbose_name='该记录是否被删除')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间', null=True, verbose_name='记录最后更新时间')),
            ],
            options={
                'verbose_name': '员工分组表',
                'verbose_name_plural': '员工分组表',
                'db_table': 'sys_group',
            },
        ),
        migrations.CreateModel(
            name='SysGroupRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.BigIntegerField(db_column='group_id', help_text='主键ID 1', verbose_name='主键ID 1')),
                ('roleId', models.BigIntegerField(db_column='role_id', help_text='主键ID 2', verbose_name='主键ID 2')),
                ('isDel', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], db_column='is_del', default=0, help_text='该记录是否被删除，0：未删除，1：已删除，默认为0', verbose_name='该记录是否被删除')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间', null=True, verbose_name='记录最后更新时间')),
            ],
            options={
                'verbose_name': '用户角色关联表',
                'verbose_name_plural': '用户角色关联表',
                'db_table': 'sys_group_role',
            },
        ),
        migrations.CreateModel(
            name='SysGroupService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.BigIntegerField(db_column='group_id', help_text='主键ID 1', verbose_name='主键ID 1')),
                ('serviceId', models.BigIntegerField(db_column='service_id', help_text='主键ID 2', verbose_name='主键ID 2')),
                ('isDel', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], db_column='is_del', default=0, help_text='该记录是否被删除，0：未删除，1：已删除，默认为0', verbose_name='该记录是否被删除')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间', null=True, verbose_name='记录最后更新时间')),
            ],
            options={
                'verbose_name': '用户服务关联表',
                'verbose_name_plural': '用户服务关联表',
                'db_table': 'sys_group_service',
            },
        ),
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('menuId', models.BigAutoField(db_column='menu_id', help_text='主键自增ID', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('menuName', models.CharField(db_column='menu_name', help_text='请输入菜单名称', max_length=32, unique=True, verbose_name='菜单名称')),
                ('menuUrl', models.CharField(db_column='menu_url', help_text='请输入菜单名称', max_length=256, verbose_name='菜单名称')),
                ('menuPriv', models.CharField(choices=[('C', 'CREATE'), ('R', 'READ'), ('U', 'UPDATE'), ('D', 'DELETE')], db_column='menu_priv', help_text='请输入菜单权限，CRUD...', max_length=32, verbose_name='菜单权限，CRUD...')),
                ('menuSort', models.SmallIntegerField(db_column='menu_sort', default=1, help_text='菜单排序', verbose_name='菜单排序')),
                ('menuStatus', models.SmallIntegerField(choices=[(0, '不可用'), (1, '可用')], db_column='menu_status', default=1, help_text='菜单状态，0：不可用，1：可用', verbose_name='菜单状态，0：不可用，1：可用')),
                ('isDel', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], db_column='is_del', default=0, help_text='该记录是否被删除，0：未删除，1：已删除，默认为0', verbose_name='该记录是否被删除')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间', null=True, verbose_name='记录最后更新时间')),
                ('menuParentId', models.ForeignKey(db_column='menu_parent_id', help_text='菜单父id', on_delete=django.db.models.deletion.CASCADE, to='account.SysMenu', verbose_name='菜单父id，外键')),
            ],
            options={
                'verbose_name': '系统菜单表',
                'verbose_name_plural': '系统菜单表',
                'db_table': 'sys_menu',
            },
        ),
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('roleId', models.BigAutoField(db_column='role_id', help_text='主键自增ID', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('roleName', models.CharField(db_column='role_name', help_text='请输入角色名称', max_length=32, unique=True, verbose_name='角色名称，唯一')),
                ('roleStatus', models.SmallIntegerField(choices=[(0, '不可用'), (1, '可用')], db_column='role_status', default=1, help_text='角色状态，0：不可用，1：可用', verbose_name='角色状态，0：不可用，1：可用')),
                ('roleDesc', models.CharField(db_column='role_desc', help_text='请输入角色描述', max_length=128, verbose_name='角色描述')),
                ('isDel', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], db_column='is_del', default=0, help_text='该记录是否被删除，0：未删除，1：已删除，默认为0', verbose_name='该记录是否被删除')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间', null=True, verbose_name='记录最后更新时间')),
            ],
            options={
                'verbose_name': '系统菜单表',
                'verbose_name_plural': '系统菜单表',
                'db_table': 'sys_role',
            },
        ),
        migrations.CreateModel(
            name='SysRoleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleId', models.BigIntegerField(db_column='role_id', help_text='主键ID 1', verbose_name='主键ID 1')),
                ('menuId', models.BigIntegerField(db_column='menu_id', help_text='主键ID 2', verbose_name='主键ID 2')),
                ('isDel', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], db_column='is_del', default=0, help_text='该记录是否被删除，0：未删除，1：已删除，默认为0', verbose_name='该记录是否被删除')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间', null=True, verbose_name='记录最后更新时间')),
            ],
            options={
                'verbose_name': '角色菜单关联表',
                'verbose_name_plural': '角色菜单关联表',
                'db_table': 'sys_role_menu',
            },
        ),
        migrations.CreateModel(
            name='SysUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.BigIntegerField(db_column='group_id', help_text='主键ID 1', verbose_name='主键ID 1')),
                ('userId', models.BigIntegerField(db_column='user_id', help_text='主键ID 2', verbose_name='主键ID 2')),
                ('isDel', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], db_column='is_del', default=0, help_text='该记录是否被删除，0：未删除，1：已删除，默认为0', verbose_name='该记录是否被删除')),
                ('createdTime', models.DateTimeField(auto_now_add=True, db_column='created_time', help_text='该记录创建时间', null=True, verbose_name='记录创建时间')),
                ('updatedTime', models.DateTimeField(auto_now=True, db_column='updated_time', help_text='记录最后更新时间', null=True, verbose_name='记录最后更新时间')),
            ],
            options={
                'verbose_name': '员工项目组关联表',
                'verbose_name_plural': '员工项目组关联表',
                'db_table': 'sys_user_group',
            },
        ),
    ]
