# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-17 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysgroupservice',
            name='serviceId',
            field=models.ForeignKey(db_index=False, help_text='服务 ID', on_delete=django.db.models.deletion.CASCADE, to='business.PrdService', verbose_name='服务 ID'),
        ),
        migrations.AddField(
            model_name='sysgrouprole',
            name='groupId',
            field=models.ForeignKey(db_index=False, help_text='用户组 ID', on_delete=django.db.models.deletion.CASCADE, to='account.SysGroup', verbose_name='用户组 ID'),
        ),
        migrations.AddField(
            model_name='sysgrouprole',
            name='roleId',
            field=models.ForeignKey(db_index=False, help_text='角色 ID', on_delete=django.db.models.deletion.CASCADE, to='account.SysRole', verbose_name='角色 ID'),
        ),
    ]
