# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-10 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170910_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='userLoginName',
            field=models.CharField(db_column='user_login_name', help_text='请输入用户登录名', max_length=32, unique=True, verbose_name='用户登录名'),
        ),
    ]
