# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-17 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.BigAutoField(max_length=20, primary_key=True, serialize=False, verbose_name='产品线编号')),
                ('product_name', models.CharField(max_length=32, verbose_name='产品线名称')),
                ('product_status', models.SmallIntegerField(choices=[(0, '未上线'), (1, '已上线'), (2, '已下线')], default=1, verbose_name='产品线状态')),
                ('product_desc', models.CharField(max_length=128, verbose_name='产品线描述')),
                ('is_del', models.SmallIntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='该记录是否被删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='记录更新时间')),
            ],
            options={
                'verbose_name': '产品线管理',
                'verbose_name_plural': '产品线管理',
            },
        ),
    ]
