# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-17 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.CharField(help_text='请输入产品线描述', max_length=128, verbose_name='产品线描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(help_text='请输入产品线名称', max_length=32, unique=True, verbose_name='产品线名称'),
        ),
    ]
