# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-17 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdbusiness',
            name='businessDesc',
            field=models.CharField(db_column='business_desc', help_text='业务线描述！', max_length=128, verbose_name='业务线描述'),
        ),
        migrations.AlterField(
            model_name='prdproduct',
            name='productDesc',
            field=models.CharField(db_column='product_desc', help_text='产品线描述！', max_length=128, verbose_name='产品线描述'),
        ),
        migrations.AlterField(
            model_name='prdservice',
            name='serviceDesc',
            field=models.CharField(db_column='service_desc', help_text='服务描述！', max_length=128, verbose_name='服务描述'),
        ),
    ]
